### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by AndreLuna6** [SistemasTecTlaxiaco/actividad-3-sintesis-AndreLuna6#2]
[Sintesis_AndreEmmanuelLunaGonzalez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-AndreLuna6/files/9447472/Sintesis_AndreEmmanuelLunaGonzalez.pdf)

**Comment by Rosa218** [comment]
Calificacion:20

**Comment by josealfredo79** [comment]
Los trabajos son individuales por favor...

**Comment by AndreLuna6** [comment]
[Sintesis1_AndreEmmanuelLunaGonzalez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-AndreLuna6/files/9472856/Sintesis1_AndreEmmanuelLunaGonzalez.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
